# Generated by Django 4.2.10 on 2024-02-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postal_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postal',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
