# Generated by Django 4.2.1 on 2024-02-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_on',
        ),
    ]
